### PR TITLE
Fix formatter instantiation

### LINKED ISSUE #111: Undefined method `source_buffer_for'  for "/code":String
```
jordan$ codeclimate analyze -f text
Starting analysis
Running eslint: Done!

== Brocfile.js (7 issues) ==
error: (NoMethodError) undefined method `source_buffer_for' for "/code":String
This is especially confusing because there is no method (or even text string) source_buffer_for anywhere in my project, which leads me to believe this error is coming from codeclimate.
```

/cc @elwayman02

### PR DESCRIPTION
**Pull request by pbrisbin**
Formatters are meant to be instantiated with an instance of FileSystem,
however when handling the -f option we were instantiating it with the raw
directory. To fix this, Formatters.resolve now returns the class itself and
the caller instantiates it with the FileSystem instance it holds already.

Fixes #111

/cc @codeclimate/review

Note: my initial attempts at getting a meaningful failing spec around this
before implementing the fix were not successful, but I should probably figure
something out along those lines before merging.

### CODE REVIEW

**Comment by wfleming** [comment]
:+1:

**Comment by pbrisbin** [comment]
I'm having a really tough time coming up with a valuable test here. If anyone has any ideas, please let know. Otherwise, I'm going to merge without it shortly.

**Comment by mxie** [comment]
@pbrisbin You could potentially do a `stub_const` on `FORMATTERS` to make sure that we're only ever passing in something that's in that array (and raise otherwise).

**Comment by pbrisbin** [comment]
Thank's @mxie , it's actually not the `resolve` method that needs testing (IMO). The original bug was in how we were instantiating the formatter (and only presented when it ultimately gets used a number of objects away), so what I'm having trouble with is finding a spec that would expose that bug...

**Comment by mxie** [comment]
Ah, I see...so it's on the `Analyze` class instead then? Could you spy on the `resolve` method?

**Comment by fhwang** [comment]
Did you consider putting an expectation on `JSONFormatter#new` to ensure it gets the filesystem argument it's expecting when a `-f` flag is passed?

**Comment by pbrisbin** [comment]
@fhwang i had originally discounted that as brittle and not meeting the "valuable" bar; it's probably better than nothing though, so I'll explore that route a bit further.

**Comment by pbrisbin** [comment]
Cool, spec added. Note: I also fixed some invalid block nesting in that spec as part of adding my new example at the end.

File: spec/cc/cli/analyze_spec.rb [hunk 1]
```diff
@@ -17,91 +17,100 @@ module CC::CLI
...
+            CC::Analyzer::EnginesRunner.expects(:new).with(anything, anything, anything, anything, paths).returns(engines_runner)
 
-              analyze.run
-            end
+            analyze.run
           end
         end
       end
+
+      describe "when a formatter argument is passed" do
```
Comment (pbrisbin) [inline spec/cc/cli/analyze_spec.rb]: This is the only actual change in this file.

**Comment by fhwang** [comment]
Yeah I'd imagine a more full-scale spec would be something on the integration level, as this bug seems to be in part due to a misunderstanding as to how the classes are supposed to interact.

Still, on its own I think this LGTM
